version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: bezyakina/yamdb:latest
    restart: always
    volumes:
      - static_volume:/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6-alpine
    restart: always
    volumes:
      - static_volume:/code/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web
