# Generated by Django 3.0.5 on 2020-10-28 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                db_column="author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор отзыва",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                db_column="title_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="api.Title",
                verbose_name="Произведение",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                db_column="author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор комментария",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                db_column="review_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.Review",
                verbose_name="Отзыв",
            ),
        ),
    ]
